### ISSUE TITLE
the service logs success while event wasn't processed successfully

### ISSUE THREAD

**Issue by nbittich** [openartcoded/dropbox-sync#13]
## Description

the service logs success while event wasn't processed successfully:;

```
dropboxsync_1    |       05/26/2022 17:00:43 | Event "InvoiceGenerated" received
dropboxsync_1    | fail: DropboxSync.BLL.Services.FileService[0]
dropboxsync_1    |       05/26/2022 17:00:43 | Could not retrieve Access Token to the API.
dropboxsync_1    | fail: DropboxSync.UIL.Managers.InvoiceManager[0]
dropboxsync_1    |       05/26/2022 17:00:43 | Couldn't save file locally
dropboxsync_1    | info: DropboxSync.UIL.BrokerEventListener[0]
dropboxsync_1    |       05/26/2022 17:00:43 | Event InvoiceGenerated treated with success!

**Comment by aspirio187** [comment]
I'm adding a new TAG to the Issue to mix it with the Issue #15 because they are both related closely related

**Comment by aspirio187** [comment]
# Issue #15 : Warn user and DLQ

## Description

When the app can't process correctly an event, it should warn the user through a mail or something that an error occured.

The service should also send a message in the DLQ on any error

## Update

When an event is unsuccessfully processed an email is sent to an email address configured in the environment variables. The event is then sent to the DLQ.
